trigger:
  branches:
    include:
      - HSA-18-sec

pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: DownloadSecureFile@1
    name: k8config
    inputs:
      secureFile: 'mzenk8-config'

  - script: |
      sudo apt-get update
      curl -LO https://dl.k8s.io/v1.32.0/bin/linux/amd64/kubectl
      sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
      mkdir -p ~/.kube
      mv $(k8config.secureFilePath) ~/.kube/config
      echo "RENDER KUBE"
      ls -a ~/.kube

    displayName: 'Setup K3s auth'

#  - task: Docker@2
#    displayName: 'Build and Push Docker image'
#    inputs:
#      containerRegistry: 'Dockerhub Connector'  # Matches the service connection name
#      repository: 'mzeng1417/hsa-image-store'
#      command: 'buildAndPush'
#      Dockerfile: '**/Dockerfile'  # Path to your Dockerfile
#      tags: |
#        latest
#        $(Build.BuildId)

  - script: |
      ./k8-push.sh
    displayName: 'Build + Push k3s'
    env: 
      DATABASE_PASSWORD: $(DATABASE_PASSWORD)
