trigger:
  branches:
    include:
    - HSA-18-sec

pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    sudo apt-get update
    sudo apt-get install -y sshpass
    mkdir -p ~/.kube
  displayName: 'Install SSHPass, Terraform, and configure kubectl'


- task: DownloadSecureFile@1
  name: k8config
  inputs:
    secureFile: 'config'

- script: |
    mkdir -p ~/.kube
    mv $(k8config.secureFilePath) ~/.kube/config
    mv $sshkey.secureFilePath) ~/.ssh/id-gcp

  displayName: 'Setup K3s auth'

- script: |
    ./k8-push.sh build
  displayName: 'Apply k3s'
  env: 
    TF_VAR_DATABASE_PASSWORD: $(DATABASE_PASSWORD)
