apiVersion: v1
kind: Pod
metadata:
  name: hsa-app
  labels:
    app: hsa-app

spec:
  containers:
  - name: hsa-app-ct
    image: mzeng1417/hsa-image-store:latest
    ports:
      - containerPort: 8000  #
    env:
      - name: DATABASE_NAME
        value: "${DATABASE_NAME}"
      - name: DATABASE_USERNAME
        value: "${DATABASE_USERNAME}"
      - name: DATABASE_IP
        value: "${DATABASE_IP}"
      - name: DATABASE_PASSWORD
        value: "${DATABASE_PASSWORD}"
  imagePullSecrets:
  - name: regcred
