# Generated by Django 5.2 on 2025-04-17 20:19

import django.db.models.deletion
import hsabackend.models.model_validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, validators=[hsabackend.models.model_validators.isNonEmpty])),
                ('last_name', models.CharField(max_length=50, validators=[hsabackend.models.model_validators.isNonEmpty])),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=10, validators=[hsabackend.models.model_validators.isValidPhone])),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, validators=[hsabackend.models.model_validators.isNonEmpty])),
                ('last_name', models.CharField(max_length=50, validators=[hsabackend.models.model_validators.isNonEmpty])),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=10, validators=[hsabackend.models.model_validators.isValidPhone])),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_name', models.CharField(max_length=100, validators=[hsabackend.models.model_validators.isNonEmpty])),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5, validators=[hsabackend.models.model_validators.is_valid_percent])),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=100, validators=[hsabackend.models.model_validators.isNonEmpty])),
                ('material_description', models.CharField(blank=True, max_length=200, null=True)),
                ('default_cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_issued', models.DateField(blank=True, default=None, null=True)),
                ('date_due', models.DateField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('created', 'created'), ('issued', 'issued'), ('paid', 'paid')], default='created', max_length=50)),
                ('sales_tax_percent', models.DecimalField(decimal_places=2, max_digits=2)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hsabackend.customer')),
                ('discounts', models.ManyToManyField(blank=True, to='hsabackend.discount')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_status', models.CharField(choices=[('created', 'created'), ('in-progress', 'in-progress'), ('completed', 'completed')], default='created', max_length=50)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('job_city', models.CharField(max_length=50, validators=[hsabackend.models.model_validators.isNonEmpty])),
                ('job_state', models.CharField(max_length=50, validators=[hsabackend.models.model_validators.isNonEmpty, hsabackend.models.model_validators.validate_state])),
                ('job_zip', models.CharField(max_length=10, validators=[hsabackend.models.model_validators.isNonEmpty])),
                ('job_address', models.CharField(max_length=100, validators=[hsabackend.models.model_validators.isNonEmpty])),
                ('use_hourly_rate', models.BooleanField(default=False)),
                ('minutes_worked', models.IntegerField(default=0)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('contractors', models.ManyToManyField(blank=True, to='hsabackend.contractor')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hsabackend.customer')),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hsabackend.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='JobsMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hsabackend.job')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hsabackend.material')),
            ],
            options={
                'db_table': 'hsabackend_job_materials',
            },
        ),
        migrations.AddField(
            model_name='job',
            name='materials',
            field=models.ManyToManyField(blank=True, through='hsabackend.JobsMaterials', to='hsabackend.material'),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=100, validators=[hsabackend.models.model_validators.isNonEmpty])),
                ('org_email', models.EmailField(max_length=100)),
                ('org_city', models.CharField(max_length=50, validators=[hsabackend.models.model_validators.isNonEmpty])),
                ('org_state', models.CharField(max_length=50, validators=[hsabackend.models.model_validators.isNonEmpty, hsabackend.models.model_validators.validate_state])),
                ('org_zip', models.CharField(max_length=10, validators=[hsabackend.models.model_validators.isNonEmpty])),
                ('org_address', models.CharField(max_length=100, validators=[hsabackend.models.model_validators.isNonEmpty])),
                ('org_phone', models.CharField(max_length=10, validators=[hsabackend.models.model_validators.isValidPhone])),
                ('org_owner_first_name', models.CharField(max_length=100, validators=[hsabackend.models.model_validators.isNonEmpty])),
                ('org_owner_last_name', models.CharField(max_length=100, validators=[hsabackend.models.model_validators.isNonEmpty])),
                ('is_onboarding', models.BooleanField(default=True)),
                ('default_labor_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('owning_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hsabackend.organization'),
        ),
        migrations.AddField(
            model_name='job',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hsabackend.organization'),
        ),
        migrations.AddField(
            model_name='discount',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hsabackend.organization'),
        ),
        migrations.AddField(
            model_name='customer',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hsabackend.organization'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hsabackend.organization'),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_first_name', models.CharField(max_length=100, validators=[hsabackend.models.model_validators.isNonEmpty])),
                ('requester_last_name', models.CharField(max_length=100, validators=[hsabackend.models.model_validators.isNonEmpty])),
                ('requester_email', models.CharField(max_length=100)),
                ('requester_city', models.CharField(max_length=50, validators=[hsabackend.models.model_validators.isNonEmpty])),
                ('requester_state', models.CharField(max_length=50, validators=[hsabackend.models.model_validators.isNonEmpty, hsabackend.models.model_validators.validate_state])),
                ('requester_zip', models.CharField(max_length=10, validators=[hsabackend.models.model_validators.isNonEmpty])),
                ('requester_address', models.CharField(max_length=100, validators=[hsabackend.models.model_validators.isNonEmpty])),
                ('requester_phone', models.CharField(blank=True, max_length=10, validators=[hsabackend.models.model_validators.isValidPhone])),
                ('description', models.CharField(max_length=200, validators=[hsabackend.models.model_validators.isNonEmpty])),
                ('availability', models.CharField(max_length=200, validators=[hsabackend.models.model_validators.isNonEmpty])),
                ('request_status', models.CharField(choices=[('received', 'received'), ('approved', 'approved')], default='received', max_length=50)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hsabackend.job')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hsabackend.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100, validators=[hsabackend.models.model_validators.isNonEmpty])),
                ('service_description', models.CharField(blank=True, max_length=200)),
                ('default_fee', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hsabackend.organization')),
            ],
        ),
        migrations.CreateModel(
            name='JobTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('materials', models.ManyToManyField(blank=True, to='hsabackend.material')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hsabackend.organization')),
                ('services', models.ManyToManyField(blank=True, to='hsabackend.service')),
            ],
        ),
        migrations.CreateModel(
            name='JobsServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hsabackend.job')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hsabackend.service')),
            ],
            options={
                'db_table': 'hsabackend_job_services',
            },
        ),
        migrations.AddField(
            model_name='job',
            name='services',
            field=models.ManyToManyField(blank=True, through='hsabackend.JobsServices', to='hsabackend.service'),
        ),
    ]
