# Generated by Django 5.1.5 on 2025-03-28 00:48

import django.db.models.deletion
import hsabackend.models.model_validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, validators=[hsabackend.models.model_validators.isNonEmpty])),
                ('last_name', models.CharField(max_length=50, validators=[hsabackend.models.model_validators.isNonEmpty])),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=10, validators=[hsabackend.models.model_validators.isValidPhone])),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, validators=[hsabackend.models.model_validators.isNonEmpty])),
                ('last_name', models.CharField(max_length=50, validators=[hsabackend.models.model_validators.isNonEmpty])),
                ('email', models.EmailField(max_length=100)),
                ('phone_no', models.CharField(max_length=10, validators=[hsabackend.models.model_validators.isValidPhone])),
                ('notes', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=100, validators=[hsabackend.models.model_validators.isNonEmpty])),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuance_date', models.DateField(blank=True, default=None, null=True)),
                ('due_date', models.DateField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('created', 'created'), ('issued', 'issued'), ('paid', 'paid')], default='created', max_length=50)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=2)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hsabackend.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_status', models.CharField(choices=[('created', 'created'), ('in-progress', 'in-progress'), ('completed', 'completed')], default='created', max_length=50)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('requestor_city', models.CharField(max_length=50, validators=[hsabackend.models.model_validators.isNonEmpty])),
                ('requestor_state', models.CharField(max_length=50, validators=[hsabackend.models.model_validators.isNonEmpty, hsabackend.models.model_validators.validate_state])),
                ('requestor_zip', models.CharField(max_length=10, validators=[hsabackend.models.model_validators.isNonEmpty])),
                ('requestor_address', models.CharField(max_length=100, validators=[hsabackend.models.model_validators.isNonEmpty])),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hsabackend.customer')),
            ],
        ),
        migrations.CreateModel(
            name='JobContractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hsabackend.contractor')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hsabackend.job')),
            ],
        ),
        migrations.CreateModel(
            name='JobMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=9)),
                ('units_used', models.IntegerField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hsabackend.job')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hsabackend.material')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=100, validators=[hsabackend.models.model_validators.isNonEmpty])),
                ('org_email', models.EmailField(max_length=100)),
                ('org_city', models.CharField(max_length=50, validators=[hsabackend.models.model_validators.isNonEmpty])),
                ('org_requestor_state', models.CharField(max_length=50, validators=[hsabackend.models.model_validators.isNonEmpty, hsabackend.models.model_validators.validate_state])),
                ('org_requestor_zip', models.CharField(max_length=10, validators=[hsabackend.models.model_validators.isNonEmpty])),
                ('org_requestor_address', models.CharField(max_length=100, validators=[hsabackend.models.model_validators.isNonEmpty])),
                ('org_phone', models.CharField(max_length=10, validators=[hsabackend.models.model_validators.isValidPhone])),
                ('org_owner_first_name', models.CharField(max_length=100, validators=[hsabackend.models.model_validators.isNonEmpty])),
                ('org_owner_last_name', models.CharField(max_length=100, validators=[hsabackend.models.model_validators.isNonEmpty])),
                ('owning_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hsabackend.organization'),
        ),
        migrations.AddField(
            model_name='job',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hsabackend.organization'),
        ),
        migrations.CreateModel(
            name='DiscountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_name', models.CharField(max_length=100, validators=[hsabackend.models.model_validators.isNonEmpty])),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5, validators=[hsabackend.models.model_validators.is_valid_percent])),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hsabackend.organization')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hsabackend.organization'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hsabackend.organization'),
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuance_date', models.DateField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('created', 'created'), ('accepted', 'accepted')], default='created', max_length=50)),
                ('material_subtotal', models.DecimalField(decimal_places=2, max_digits=9)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('discount_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hsabackend.discounttype')),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hsabackend.invoice')),
                ('jobID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hsabackend.job')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100, validators=[hsabackend.models.model_validators.isNonEmpty])),
                ('service_description', models.CharField(blank=True, max_length=200)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hsabackend.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestor_first_name', models.CharField(max_length=100, validators=[hsabackend.models.model_validators.isNonEmpty])),
                ('requestor_last_name', models.CharField(max_length=100, validators=[hsabackend.models.model_validators.isNonEmpty])),
                ('requestor_email', models.CharField(max_length=100)),
                ('requestor_city', models.CharField(max_length=50, validators=[hsabackend.models.model_validators.isNonEmpty])),
                ('requestor_state', models.CharField(max_length=50, validators=[hsabackend.models.model_validators.isNonEmpty, hsabackend.models.model_validators.validate_state])),
                ('requestor_zip', models.CharField(max_length=10, validators=[hsabackend.models.model_validators.isNonEmpty])),
                ('requestor_address', models.CharField(max_length=100, validators=[hsabackend.models.model_validators.isNonEmpty])),
                ('requestor_phone_no', models.CharField(max_length=10, validators=[hsabackend.models.model_validators.isValidPhone])),
                ('description', models.CharField(max_length=200, validators=[hsabackend.models.model_validators.isNonEmpty])),
                ('status', models.CharField(choices=[('received', 'received'), ('approved', 'approved')], default='received', max_length=50)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hsabackend.organization')),
                ('service', models.ManyToManyField(to='hsabackend.service')),
            ],
        ),
        migrations.CreateModel(
            name='JobTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(verbose_name=200)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hsabackend.organization')),
                ('service', models.ManyToManyField(to='hsabackend.service')),
            ],
        ),
        migrations.CreateModel(
            name='JobService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hsabackend.job')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hsabackend.service')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('job_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hsabackend.jobtemplate')),
            ],
        ),
    ]
