# Generated by Django 5.2 on 2025-04-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsabackend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='default_payment_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='sales_tax_percent',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
