# Generated by Django 5.2 on 2025-04-25 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hsabackend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='material_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='material',
            old_name='material_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='service_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='service_name',
            new_name='name',
        ),
    ]
