# Generated by Django 5.1.5 on 2025-02-27 00:18

import hsabackend.models.model_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsabackend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='requestor_address',
            field=models.CharField(default='None', max_length=100, validators=[hsabackend.models.model_validators.isNonEmpty]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='requestor_city',
            field=models.CharField(default='None', max_length=50, validators=[hsabackend.models.model_validators.isNonEmpty]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='requestor_state',
            field=models.CharField(default='None', max_length=50, validators=[hsabackend.models.model_validators.isNonEmpty, hsabackend.models.model_validators.validate_state]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='requestor_zip',
            field=models.CharField(default='None', max_length=10, validators=[hsabackend.models.model_validators.isNonEmpty]),
            preserve_default=False,
        ),
    ]
