# Generated by Django 5.1.5 on 2025-03-19 22:51

import hsabackend.models.model_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsabackend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discounttype',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[hsabackend.models.model_validators.is_valid_percent]),
        ),
    ]
