# Generated by Django 5.1.5 on 2025-03-28 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hsabackend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobmaterial',
            name='job',
        ),
        migrations.RemoveField(
            model_name='jobmaterial',
            name='material',
        ),
        migrations.RemoveField(
            model_name='jobservice',
            name='job',
        ),
        migrations.RemoveField(
            model_name='jobservice',
            name='service',
        ),
        migrations.DeleteModel(
            name='JobContractor',
        ),
        migrations.DeleteModel(
            name='JobMaterial',
        ),
        migrations.DeleteModel(
            name='JobService',
        ),
    ]
