# Generated by Django 5.1.5 on 2025-02-05 06:25

import hsabackend.models.model_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsabackend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobtemplate',
            old_name='job_template',
            new_name='service',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='org_address',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='org_owner_name',
        ),
        migrations.AddField(
            model_name='inovice',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('issued', 'issued'), ('paid', 'paid')], default='created', max_length=50),
        ),
        migrations.AddField(
            model_name='organization',
            name='org_city',
            field=models.CharField(default='New York City', max_length=50, validators=[hsabackend.models.model_validators.isNonEmpty]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='org_owner_first_name',
            field=models.CharField(default='Jane', max_length=100, validators=[hsabackend.models.model_validators.isNonEmpty]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='org_owner_last_name',
            field=models.CharField(default='Doe', max_length=100, validators=[hsabackend.models.model_validators.isNonEmpty]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='org_requestor_address',
            field=models.CharField(default='1000 Box Lane', max_length=100, validators=[hsabackend.models.model_validators.isNonEmpty]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='org_requestor_state',
            field=models.CharField(default='New York', max_length=50, validators=[hsabackend.models.model_validators.isNonEmpty]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='org_requestor_zip',
            field=models.CharField(default='55555', max_length=10, validators=[hsabackend.models.model_validators.isNonEmpty]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contractor',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='first_name',
            field=models.CharField(max_length=50, validators=[hsabackend.models.model_validators.isNonEmpty]),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='last_name',
            field=models.CharField(max_length=50, validators=[hsabackend.models.model_validators.isNonEmpty]),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='phone',
            field=models.CharField(max_length=10, validators=[hsabackend.models.model_validators.isValidPhone]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(validators=[hsabackend.models.model_validators.isNonEmpty], verbose_name=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(validators=[hsabackend.models.model_validators.isNonEmpty], verbose_name=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_no',
            field=models.CharField(max_length=10, validators=[hsabackend.models.model_validators.isValidPhone]),
        ),
        migrations.AlterField(
            model_name='discounttype',
            name='discount_name',
            field=models.CharField(max_length=100, validators=[hsabackend.models.model_validators.isNonEmpty]),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_status',
            field=models.CharField(choices=[('created', 'created'), ('completed', 'completed')], default='created', max_length=50),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_name',
            field=models.CharField(max_length=100, validators=[hsabackend.models.model_validators.isNonEmpty]),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='organization',
            name='org_name',
            field=models.CharField(max_length=100, validators=[hsabackend.models.model_validators.isNonEmpty]),
        ),
        migrations.AlterField(
            model_name='quote',
            name='material_subtotal',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('accepted', 'accepted')], default='created', max_length=50),
        ),
        migrations.AlterField(
            model_name='quote',
            name='total_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='description',
            field=models.CharField(max_length=200, validators=[hsabackend.models.model_validators.isNonEmpty]),
        ),
        migrations.AlterField(
            model_name='request',
            name='requestor_address',
            field=models.CharField(max_length=100, validators=[hsabackend.models.model_validators.isNonEmpty]),
        ),
        migrations.AlterField(
            model_name='request',
            name='requestor_city',
            field=models.CharField(max_length=50, validators=[hsabackend.models.model_validators.isNonEmpty]),
        ),
        migrations.AlterField(
            model_name='request',
            name='requestor_name',
            field=models.CharField(max_length=100, validators=[hsabackend.models.model_validators.isNonEmpty]),
        ),
        migrations.AlterField(
            model_name='request',
            name='requestor_state',
            field=models.CharField(max_length=50, validators=[hsabackend.models.model_validators.isNonEmpty]),
        ),
        migrations.AlterField(
            model_name='request',
            name='requestor_zip',
            field=models.CharField(max_length=10, validators=[hsabackend.models.model_validators.isNonEmpty]),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('received', 'received'), ('approved', 'approved')], default='received', max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_name',
            field=models.CharField(max_length=100, validators=[hsabackend.models.model_validators.isNonEmpty]),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.FloatField(),
        ),
    ]
