# Generated by Django 5.1.5 on 2025-04-05 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hsabackend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobtemplate',
            name='service',
        ),
    ]
