# Generated by Django 5.1.5 on 2025-04-11 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsabackend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_onboarding',
            field=models.BooleanField(default=True),
        ),
    ]
