# Generated by Django 5.2 on 2025-04-06 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hsabackend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='phone_no',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='requestor_phone_no',
            new_name='requestor_phone',
        ),
    ]
