# Generated by Django 5.1.5 on 2025-03-22 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsabackend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_status',
            field=models.CharField(choices=[('created', 'created'), ('in-progress', 'in-progress'), ('completed', 'completed')], default='created', max_length=50),
        ),
    ]
