# Generated by Django 5.2 on 2025-04-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsabackend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='default_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
