# Generated by Django 5.1.5 on 2025-03-22 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsabackend', '0002_invoice_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmaterial',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
