# Generated by Django 5.1.5 on 2025-03-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsabackend', '0002_invoice_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='services',
            field=models.ManyToManyField(to='hsabackend.service'),
        ),
    ]
