# Generated by Django 5.2 on 2025-04-25 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsabackend', '0002_rename_material_description_material_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hsabackend.job'),
        ),
    ]
