# Generated by Django 5.1.5 on 2025-04-05 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsabackend', '0002_remove_jobtemplate_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTemplateMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=9)),
                ('units_used', models.IntegerField()),
                ('jobtemplate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hsabackend.jobtemplate')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hsabackend.material')),
            ],
        ),
        migrations.CreateModel(
            name='JobTemplateService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hsabackend.jobtemplate')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hsabackend.service')),
            ],
        ),
    ]
