# Generated by Django 5.2 on 2025-04-22 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsabackend', '0002_invoice_payment_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hsabackend.customer'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_status',
            field=models.CharField(choices=[('created', 'created'), ('in-progress', 'in-progress'), ('completed', 'completed'), ('rejected', 'rejected')], default='created', max_length=50),
        ),
    ]
