# Generated by Django 5.2 on 2025-04-06 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsabackend', '0002_rename_phone_no_customer_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='notes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
