# Generated by Django 5.2 on 2025-04-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsabackend', '0002_material_default_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='default_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='service',
            name='default_hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
