# Generated by Django 5.1.5 on 2025-04-20 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsabackend', '0002_organization_is_onboarding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('booking_type', models.CharField(choices=[('job', 'job'), ('quote', 'quote')], default='job', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected'), ('cancelled', 'cancelled')], default='pending', max_length=50)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hsabackend.job')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hsabackend.organization')),
            ],
        ),
    ]
