# Generated by Django 5.1.5 on 2025-03-01 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsabackend', '0003_alter_job_description_alter_job_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='customer',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='hsabackend.customer'),
            preserve_default=False,
        ),
    ]
