# Generated by Django 5.2 on 2025-04-10 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hsabackend', '0003_alter_material_default_cost_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='default_hourly_rate',
            new_name='default_rate',
        ),
    ]
