# Generated by Django 5.2 on 2025-04-06 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hsabackend', '0003_alter_customer_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='requestor_address',
            new_name='requester_address',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='requestor_city',
            new_name='requester_city',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='requestor_state',
            new_name='requester_state',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='requestor_zip',
            new_name='requester_zip',
        ),
    ]
