# Generated by Django 5.1.5 on 2025-04-20 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsabackend', '0003_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='event_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
