# Generated by Django 5.1.5 on 2025-04-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsabackend', '0003_jobtemplatematerial_jobtemplateservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtemplate',
            name='name',
            field=models.CharField(null=True, verbose_name=200),
        ),
    ]
