# Generated by Django 5.2 on 2025-04-27 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsabackend', '0003_alter_request_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsmaterials',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
