# Generated by Django 5.1.5 on 2025-03-01 16:49

import hsabackend.models.model_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsabackend', '0004_job_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='requestor_name',
            new_name='requestor_first_name',
        ),
        migrations.AddField(
            model_name='request',
            name='requestor_last_name',
            field=models.CharField(default='last', max_length=100, validators=[hsabackend.models.model_validators.isNonEmpty]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='requestor_phone_no',
            field=models.CharField(default='1231231234', max_length=10, validators=[hsabackend.models.model_validators.isValidPhone]),
            preserve_default=False,
        ),
    ]
