# Generated by Django 5.2 on 2025-04-27 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsabackend', '0004_alter_jobsmaterials_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hsabackend.job'),
        ),
    ]
