# Generated by Django 5.2 on 2025-04-22 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsabackend', '0004_alter_jobsmaterials_unit_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsmaterials',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
