# Generated by Django 5.2 on 2025-04-11 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hsabackend', '0004_rename_default_hourly_rate_service_default_rate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
