# Generated by Django 5.1.5 on 2025-04-20 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsabackend', '0004_booking_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='back_color',
            field=models.CharField(default='#6aa84f', max_length=50),
        ),
    ]
