# Generated by Django 5.1.5 on 2025-04-05 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hsabackend', '0004_jobtemplate_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobtemplatematerial',
            old_name='jobtemplate',
            new_name='job_template',
        ),
    ]
