# Generated by Django 5.2 on 2025-04-07 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hsabackend', '0004_rename_requestor_address_job_requester_address_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DiscountType',
            new_name='Discount',
        ),
    ]
