# Generated by Django 5.1.5 on 2025-03-02 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsabackend', '0005_rename_requestor_name_request_requestor_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='notes',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
