# Generated by Django 5.2 on 2025-04-07 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsabackend', '0005_rename_discounttype_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='material_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
