# Generated by Django 5.1.5 on 2025-04-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsabackend', '0005_booking_back_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='back_color',
            field=models.CharField(blank=True, default='#6aa84f', max_length=50),
        ),
    ]
