# Generated by Django 5.1.5 on 2025-03-08 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsabackend', '0006_alter_customer_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hsabackend.invoice'),
        ),
    ]
