# Generated by Django 5.1.5 on 2025-04-25 20:12

import django.db.models.deletion
import django.utils.timezone
import hsabackend.models.model_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsabackend', '0006_alter_booking_back_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='status',
            new_name='request_status',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='requestor_address',
            new_name='requester_address',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='requestor_city',
            new_name='requester_city',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='requestor_email',
            new_name='requester_email',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='requestor_first_name',
            new_name='requester_first_name',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='requestor_last_name',
            new_name='requester_last_name',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='requestor_state',
            new_name='requester_state',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='requestor_zip',
            new_name='requester_zip',
        ),
        migrations.RemoveField(
            model_name='request',
            name='requestor_phone_no',
        ),
        migrations.RemoveField(
            model_name='request',
            name='service',
        ),
        migrations.AddField(
            model_name='request',
            name='availability',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, validators=[hsabackend.models.model_validators.is_non_empty]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hsabackend.job'),
        ),
        migrations.AddField(
            model_name='request',
            name='requester_phone',
            field=models.CharField(blank=True, max_length=10, validators=[hsabackend.models.model_validators.is_valid_phone]),
        ),
    ]
