# Generated by Django 5.1.5 on 2025-03-09 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsabackend', '0007_quote_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(blank=True),
        ),
    ]
