# Generated by Django 5.1.5 on 2025-05-02 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsabackend', '0007_rename_status_request_request_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hsabackend.job'),
        ),
    ]
