# Generated by Django 5.1.5 on 2025-04-29 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsabackend', '0007_rename_status_request_request_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='quote_s3_link',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='quote_sign_pin',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='request',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hsabackend.job'),
        ),
    ]
