# Generated by Django 5.1.5 on 2025-03-09 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsabackend', '0008_alter_invoice_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='price',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(blank=True, default=None),
        ),
    ]
