# Generated by Django 5.1.5 on 2025-05-03 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsabackend', '0009_job_quote_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='quote_s3_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='quote_sign_pin',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
