# Generated by Django 5.1.5 on 2025-05-04 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hsabackend', '0008_alter_request_job'),
        ('hsabackend', '0010_alter_job_quote_s3_link_alter_job_quote_sign_pin'),
    ]

    operations = [
    ]
