# Generated by Django 5.1.5 on 2025-03-12 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsabackend', '0011_alter_invoice_due_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MaterialJob',
            new_name='JobMaterial',
        ),
        migrations.RemoveField(
            model_name='job',
            name='contractor',
        ),
        migrations.RemoveField(
            model_name='job',
            name='materials',
        ),
        migrations.RemoveField(
            model_name='job',
            name='service',
        ),
        migrations.AlterField(
            model_name='quote',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hsabackend.invoice'),
        ),
        migrations.CreateModel(
            name='JobContractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hsabackend.contractor')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hsabackend.job')),
            ],
        ),
        migrations.CreateModel(
            name='JobService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hsabackend.job')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hsabackend.service')),
            ],
        ),
    ]
