# Generated by Django 5.1.5 on 2025-05-06 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hsabackend', '0011_merge_20250504_0016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='quote_sign_pin',
        ),
    ]
