# Generated by Django 5.1.5 on 2025-05-05 23:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsabackend', '0011_merge_20250504_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='flat_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='job',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='job',
            name='minutes_worked',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
    ]
