# Generated by Django 5.1.5 on 2025-03-14 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsabackend', '0011_alter_invoice_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discounttype',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='jobmaterial',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='quote',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hsabackend.invoice'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='material_subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='quote',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
