# Generated by Django 5.1.5 on 2025-03-16 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsabackend', '0012_alter_discounttype_discount_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='issuance_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
