# Generated by Django 5.1.5 on 2025-05-06 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsabackend', '0012_job_flat_fee_job_hourly_rate_job_minutes_worked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hsabackend.invoice'),
        ),
    ]
