# Generated by Django 5.1.5 on 2025-03-14 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hsabackend', '0012_rename_materialjob_jobmaterial_remove_job_contractor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobmaterial',
            old_name='unit_cost',
            new_name='price_per_unit',
        ),
    ]
