# Generated by Django 5.1.5 on 2025-05-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsabackend', '0013_job_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='tax',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
