# Generated by Django 5.1.5 on 2025-03-19 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hsabackend', '0013_alter_invoice_issuance_date'),
        ('hsabackend', '0013_rename_unit_cost_jobmaterial_price_per_unit'),
    ]

    operations = [
    ]
