# Generated by Django 5.1.5 on 2025-05-06 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hsabackend', '0012_remove_job_quote_sign_pin'),
        ('hsabackend', '0014_alter_invoice_tax'),
    ]

    operations = [
    ]
