# Generated by Django 5.1.5 on 2025-05-07 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsabackend', '0015_merge_20250506_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discounts',
            field=models.ManyToManyField(blank=True, to='hsabackend.discounttype'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_link',
            field=models.URLField(blank=True),
        ),
    ]
