# Generated by Django 5.1.5 on 2025-05-06 23:59

import hsabackend.models.model_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsabackend', '0015_merge_20250506_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_url',
            field=models.CharField(blank=True, max_length=300, null=True, validators=[hsabackend.models.model_validators.isNonEmpty, hsabackend.models.model_validators.is_valid_http_url]),
        ),
        migrations.AddField(
            model_name='organization',
            name='default_payment_url',
            field=models.CharField(blank=True, max_length=300, null=True, validators=[hsabackend.models.model_validators.isNonEmpty, hsabackend.models.model_validators.is_valid_http_url]),
        ),
    ]
