# Generated by Django 5.1.5 on 2025-05-08 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hsabackend', '0016_invoice_payment_url_organization_default_payment_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='notified',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
